import React from "react";
import { BrowserRouter, Route, Routes } from "react-router-dom";
import ClassIndex from "./Component/ClassIndex/ClassIndex";
import Program from "./Component/Program/Program";
import Layout from "./Layout/Layout";

const api = 'http://127.0.0.1:8000/api/';
export const host = (data, value = {}) => {
    var search = [];
    for (const key in value) {
        search.push(`${key}=${value[key]}`)
    }
    return api + data + '?' + search.join('&');
};
export const format = (data) => data.map((e, i) => ({ 'index': i + 1, 'key': e.id, ...e }));

export default function App(data) {
    return (
        <Layout>
            <BrowserRouter>
                <Routes>
                    <Route path="/" element={<ClassIndex />} />
                    <Route path="/program/:name/:id" element={<Program/>}/> 
                </Routes>
            </BrowserRouter>
        </Layout>
    );
}

export const colorList = [
    { name: "Absolute Zero", code: "#0048BA" },
    { name: "Acid green", code: "#B0BF1A" },
    { name: "Aero", code: "#7CB9E8" },
    { name: "Aero blue", code: "#C0E8D5" },
    { name: "African violet", code: "#B284BE" },
    { name: "Air superiority blue", code: "#72A0C1" },
    { name: "Alabaster", code: "#EDEAE0" },
    { name: "Alizarin", code: "#DB2D43" },
    { name: "Alice blue", code: "#F0F8FF" },
    { name: "Alloy orange", code: "#C46210" },
    { name: "Almond", code: "#EFDECD" },
    { name: "Amaranth", code: "#E52B50" },
    { name: "Amaranth(M & P)", code: "#9F2B68" },
    { name: "Amaranth pink", code: "#F19CBB" },
    { name: "Amaranth purple", code: "#AB274F" },
    { name: "Amaranth red", code: "#D3212D" },
    { name: "Amazon", code: "#3B7A57" },
    { name: "Amber", code: "#FFBF00" },
    { name: "Amber(SAE / ECE)", code: "#FF7E00" },
    { name: "Amethyst", code: "#9966CC" },
    { name: "Android green", code: "#3DDC84" },
    { name: "Antique brass", code: "#CD9575" },
    { name: "Antique bronze", code: "#665D1E" },
    { name: "Antique fuchsia", code: "#915C83" },
    { name: "Antique ruby", code: "#841B2D" },
    { name: "Antique white", code: "#FAEBD7" },
    { name: "Ao(English)", code: "#008000" },
    { name: "Apple green", code: "#8DB600" },
    { name: "Apricot", code: "#FBCEB1" },
    { name: "Aqua", code: "#00FFFF" },
    { name: "Aquamarine", code: "#7FFFD4" },
    { name: "Arctic lime", code: "#D0FF14" },
    { name: "Army green", code: "#4B5320" },
    { name: "Artichoke", code: "#8F9779" },
    { name: "Arylide yellow", code: "#E9D66B" },
    { name: "Ash gray", code: "#B2BEB5" },
    { name: "Asparagus", code: "#87A96B" },
    { name: "Astronaut", code: "#27346F" },
    { name: "Atomic tangerine", code: "#FF9966" },
    { name: "Auburn", code: "#A52A2A" },
    { name: "Aureolin", code: "#FDEE00" },
    { name: "Avocado", code: "#568203" },
    { name: "Azure", code: "#007FFF" },
    { name: "Azure(X11 / web color)", code: "#F0FFFF" },
    { name: "Baby blue", code: "#89CFF0" },
    { name: "Baby blue eyes", code: "#A1CAF1" },
    { name: "Baby pink", code: "#F4C2C2" },
    { name: "Baby powder", code: "#FEFEFA" },
    { name: "Baker - Miller pink", code: "#FF91AF" },
    { name: "Banana Mania", code: "#FAE7B5" },
    { name: "Barbie Pink", code: "#DA1884" },
    { name: "Barn red", code: "#7C0A02" },
    { name: "Battleship grey", code: "#848482" },
    { name: "Beau blue", code: "#BCD4E6" },
    { name: "Beaver", code: "#9F8170" },
    { name: "Beige", code: "#F5F5DC" },
    { name: "B'dazzled blue", code: "#2E5894" },
    { name: "Big dip o’ruby", code: "#9C2542" },
    { name: "Bisque", code: "#FFE4C4" },
    { name: "Bistre", code: "#3D2B1F" },
    { name: "Bistre brown", code: "#967117" },
    { name: "Bitter lemon", code: "#CAE00D" },
    { name: "Bitter lime", code: "#BFFF00" },
    { name: "Bittersweet", code: "#FE6F5E" },
    { name: "Bittersweet shimmer", code: "#BF4F51" },
    { name: "Black", code: "#000000" },
    { name: "Black bean", code: "#3D0C02" },
    { name: "Black chocolate", code: "#1B1811" },
    { name: "Black coffee", code: "#3B2F2F" },
    { name: "Black coral", code: "#54626F" },
    { name: "Black olive", code: "#3B3C36" },
    { name: "Black Shadows", code: "#BFAFB2" },
    { name: "Blanched almond", code: "#FFEBCD" },
    { name: "Blast - off bronze", code: "#A57164" },
    { name: "Bleu de France", code: "#318CE7" },
    { name: "Blizzard blue", code: "#ACE5EE" },
    { name: "Blond", code: "#FAF0BE" },
    { name: "Blood red", code: "#660000" },
    { name: "Blue", code: "#0000FF" },
    { name: "Blue(Crayola)", code: "#1F75FE" },
    { name: "Blue(Munsell)", code: "#0093AF" },
    { name: "Blue(NCS)", code: "#0087BD" },
    { name: "Blue(Pantone)", code: "#0018A8" },
    { name: "Blue(pigment)", code: "#333399" },
    { name: "Blue(RYB)", code: "#0247FE" },
    { name: "Blue bell", code: "#A2A2D0" },
    { name: "Blue - gray", code: "#6699CC" },
    { name: "Blue - green", code: "#0D98BA" },
    { name: "Blue - green(color wheel)", code: "#064E40" },
    { name: "Blue jeans", code: "#5DADEC" },
    { name: "Blue sapphire", code: "#126180" },
    { name: "Blue - violet", code: "#8A2BE2" },
    { name: "Blue - violet(Crayola)", code: "#7366BD" },
    { name: "Blue - violet(color wheel)", code: "#4D1A7F" },
    { name: "Blue yonder", code: "#5072A7" },
    { name: "Bluetiful", code: "#3C69E7" },
    { name: "Blush", code: "#DE5D83" },
    { name: "Bole", code: "#79443B" },
    { name: "Bone", code: "#E3DAC9" },
    { name: "Bottle green", code: "#006A4E" },
    { name: "Brandy", code: "#87413F" },
    { name: "Brick red", code: "#CB4154" },
    { name: "Bright green", code: "#66FF00" },
    { name: "Bright lilac", code: "#D891EF" },
    { name: "Bright maroon", code: "#C32148" },
    { name: "Bright navy blue", code: "#1974D2" },
    { name: "Bright yellow(Crayola)", code: "#FFAA1D" },
    { name: "Brilliant rose", code: "#FF55A3" },
    { name: "Brink pink", code: "#FB607F" },
    { name: "British racing green", code: "#004225" },
    { name: "Bronze", code: "#CD7F32" },
    { name: "Brown", code: "#88540B" },
    { name: "Brown sugar", code: "#AF6E4D" },
    { name: "Brunswick green", code: "#1B4D3E" },
    { name: "Bud green", code: "#7BB661" },
    { name: "Buff", code: "#FFC680" },
    { name: "Burgundy", code: "#800020" },
    { name: "Burlywood", code: "#DEB887" },
    { name: "Burnished brown", code: "#A17A74" },
    { name: "Burnt orange", code: "#CC5500" },
    { name: "Burnt sienna", code: "#E97451" },
    { name: "Burnt umber", code: "#8A3324" },
    { name: "Byzantine", code: "#BD33A4" },
    { name: "Byzantium", code: "#702963" },
    { name: "Cadet", code: "#536872" },
    { name: "Cadet blue", code: "#5F9EA0" },
    { name: "Cadet blue(Crayola)", code: "#A9B2C3" },
    { name: "Cadet grey", code: "#91A3B0" },
    { name: "Cadmium green", code: "#006B3C" },
    { name: "Cadmium orange", code: "#ED872D" },
    { name: "Cadmium red", code: "#E30022" },
    { name: "Cadmium yellow", code: "#FFF600" },
    { name: "Café au lait", code: "#A67B5B" },
    { name: "Café noir", code: "#4B3621" },
    { name: "Cambridge blue", code: "#A3C1AD" },
    { name: "Camel", code: "#C19A6B" },
    { name: "Cameo pink", code: "#EFBBCC" },
    { name: "Canary", code: "#FFFF99" },
    { name: "Canary yellow", code: "#FFEF00" },
    { name: "Candy apple red", code: "#FF0800" },
    { name: "Candy pink", code: "#E4717A" },
    { name: "Capri", code: "#00BFFF" },
    { name: "Caput mortuum", code: "#592720" },
    { name: "Cardinal", code: "#C41E3A" },
    { name: "Caribbean green", code: "#00CC99" },
    { name: "Carmine", code: "#960018" },
    { name: "Carmine(M & P)", code: "#D70040" },
    { name: "Carnation pink", code: "#FFA6C9" },
    { name: "Carnelian", code: "#B31B1B" },
    { name: "Carolina blue", code: "#56A0D3" },
    { name: "Carrot orange", code: "#ED9121" },
    { name: "Castleton green", code: "#00563F" },
    { name: "Catawba", code: "#703642" },
    { name: "Cedar Chest", code: "#C95A49" },
    { name: "Celadon", code: "#ACE1AF" },
    { name: "Celadon blue", code: "#007BA7" },
    { name: "Celadon green", code: "#2F847C" },
    { name: "Celeste", code: "#B2FFFF" },
    { name: "Celtic blue", code: "#246BCE" },
    { name: "Cerise", code: "#DE3163" },
    { name: "Cerulean", code: "#007BA7" },
    { name: "Cerulean blue", code: "#2A52BE" },
    { name: "Cerulean frost", code: "#6D9BC3" },
    { name: "Cerulean(Crayola)", code: "#1DACD6" },
    { name: "CG blue", code: "#007AA5" },
    { name: "CG red", code: "#E03C31" },
    { name: "Champagne", code: "#F7E7CE" },
    { name: "Champagne pink", code: "#F1DDCF" },
    { name: "Charcoal", code: "#36454F" },
    { name: "Charleston green", code: "#232B2B" },
    { name: "Charm pink", code: "#E68FAC" },
    { name: "Chartreuse(traditional)", code: "#DFFF00" },
    { name: "Chartreuse(web)", code: "#7FFF00" },
    { name: "Cherry blossom pink", code: "#FFB7C5" },
    { name: "Chestnut", code: "#954535" },
    { name: "Chili red", code: "#E23D28" },
    { name: "China pink", code: "#DE6FA1" },
    { name: "China rose", code: "#A8516E" },
    { name: "Chinese red", code: "#AA381E" },
    { name: "Chinese violet", code: "#856088" },
    { name: "Chinese yellow", code: "#FFB200" },
    { name: "Chocolate(traditional)", code: "#7B3F00" },
    { name: "Chocolate(web)", code: "#D2691E" },
    { name: "Chocolate Cosmos", code: "#58111A" },
    { name: "Chrome yellow", code: "#FFA700" },
    { name: "Cinereous", code: "#98817B" },
    { name: "Cinnabar", code: "#E34234" },
    { name: "Cinnamon Satin", code: "#CD607E" },
    { name: "Citrine", code: "#E4D00A" },
    { name: "Citron", code: "#9FA91F" },
    { name: "Claret", code: "#7F1734" },
    { name: "Cobalt blue", code: "#0047AB" },
    { name: "Cocoa brown", code: "#D2691E" },
    { name: "Coffee", code: "#6F4E37" },
    { name: "Columbia Blue", code: "#B9D9EB" },
    { name: "Congo pink", code: "#F88379" },
    { name: "Cool grey", code: "#8C92AC" },
    { name: "Copper", code: "#B87333" },
    { name: "Copper(Crayola)", code: "#DA8A67" },
    { name: "Copper penny", code: "#AD6F69" },
    { name: "Copper red", code: "#CB6D51" },
    { name: "Copper rose", code: "#996666" },
    { name: "Coquelicot", code: "#FF3800" },
    { name: "Coral", code: "#FF7F50" },
    { name: "Coral pink", code: "#F88379" },
    { name: "Cordovan", code: "#893F45" },
    { name: "Corn", code: "#FBEC5D" },
    { name: "Cornell red", code: "#B31B1B" },
    { name: "Cornflower blue", code: "#6495ED" },
    { name: "Cornsilk", code: "#FFF8DC" },
    { name: "Cosmic cobalt", code: "#2E2D88" },
    { name: "Cosmic latte", code: "#FFF8E7" },
    { name: "Coyote brown", code: "#81613C" },
    { name: "Cotton candy", code: "#FFBCD9" },
    { name: "Cream", code: "#FFFDD0" },
    { name: "Crimson", code: "#DC143C" },
    { name: "Crimson(UA)", code: "#9E1B32" },
    { name: "Crystal", code: "#A7D8DE" },
    { name: "Cultured", code: "#F5F5F5" },
    { name: "Cyan", code: "#00FFFF" },
    { name: "Cyan(process)", code: "#00B7EB" },
    { name: "Cyber grape", code: "#58427C" },
    { name: "Cyber yellow", code: "#FFD300" },
    { name: "Cyclamen", code: "#F56FA1" },
    { name: "Dark blue - gray", code: "#666699" },
    { name: "Dark brown", code: "#654321" },
    { name: "Dark byzantium", code: "#5D3954" },
    { name: "Dark cornflower blue", code: "#26428B" },
    { name: "Dark cyan", code: "#008B8B" },
    { name: "Dark electric blue", code: "#536878" },
    { name: "Dark goldenrod", code: "#B8860B" },
    { name: "Dark green", code: "#013220" },
    { name: "Dark green(X11)", code: "#006400" },
    { name: "Dark jungle green", code: "#1A2421" },
    { name: "Dark khaki", code: "#BDB76B" },
    { name: "Dark lava", code: "#483C32" },
    { name: "Dark liver", code: "#534B4F" },
    { name: "Dark liver(horses)", code: "#543D37" },
    { name: "Dark magenta", code: "#8B008B" },
    { name: "Dark moss green", code: "#4A5D23" },
    { name: "Dark olive green", code: "#556B2F" },
    { name: "Dark orange", code: "#FF8C00" },
    { name: "Dark orchid", code: "#9932CC" },
    { name: "Dark pastel green", code: "#03C03C" },
    { name: "Dark purple", code: "#301934" },
    { name: "Dark red", code: "#8B0000" },
    { name: "Dark salmon", code: "#E9967A" },
    { name: "Dark sea green", code: "#8FBC8F" },
    { name: "Dark sienna", code: "#3C1414" },
    { name: "Dark sky blue", code: "#8CBED6" },
    { name: "Dark slate blue", code: "#483D8B" },
    { name: "Dark slate gray", code: "#2F4F4F" },
    { name: "Dark spring green", code: "#177245" },
    { name: "Dark turquoise", code: "#00CED1" },
    { name: "Dark violet", code: "#9400D3" },
    { name: "Dartmouth green", code: "#00703C" },
    { name: "Davy's grey", code: "#555555" },
    { name: "Deep cerise", code: "#DA3287" },
    { name: "Deep champagne", code: "#FAD6A5" },
    { name: "Deep chestnut", code: "#B94E48" },
    { name: "Deep jungle green", code: "#004B49" },
    { name: "Deep pink", code: "#FF1493" },
    { name: "Deep saffron", code: "#FF9933" },
    { name: "Deep sky blue", code: "#00BFFF" },
    { name: "Deep Space Sparkle", code: "#4A646C" },
    { name: "Deep taupe", code: "#7E5E60" },
    { name: "Denim", code: "#1560BD" },
    { name: "Denim blue", code: "#2243B6" },
    { name: "Desert", code: "#C19A6B" },
    { name: "Desert sand", code: "#EDC9AF" },
    { name: "Dim gray", code: "#696969" },
    { name: "Dodger blue", code: "#1E90FF" },
    { name: "Dogwood rose", code: "#D71868" },
    { name: "Drab", code: "#967117" },
    { name: "Duke blue", code: "#00009C" },
    { name: "Dutch white", code: "#EFDFBB" },
    { name: "Earth yellow", code: "#E1A95F" },
    { name: "Ebony", code: "#555D50" },
    { name: "Ecru", code: "#C2B280" },
    { name: "Eerie black", code: "#1B1B1B" },
    { name: "Eggplant", code: "#614051" },
    { name: "Eggshell", code: "#F0EAD6" },
    { name: "Egyptian blue", code: "#1034A6" },
    { name: "Eigengrau", code: "#16161D" },
    { name: "Electric blue", code: "#7DF9FF" },
    { name: "Electric green", code: "#00FF00" },
    { name: "Electric indigo", code: "#6F00FF" },
    { name: "Electric lime", code: "#CCFF00" },
    { name: "Electric purple", code: "#BF00FF" },
    { name: "Electric violet", code: "#8F00FF" },
    { name: "Emerald", code: "#50C878" },
    { name: "Eminence", code: "#6C3082" },
    { name: "English green", code: "#1B4D3E" },
    { name: "English lavender", code: "#B48395" },
    { name: "English red", code: "#AB4B52" },
    { name: "English vermillion", code: "#CC474B" },
    { name: "English violet", code: "#563C5C" },
    { name: "Erin", code: "#00FF40" },
    { name: "Eton blue", code: "#96C8A2" },
    { name: "Fallow", code: "#C19A6B" },
    { name: "Falu red", code: "#801818" },
    { name: "Fandango", code: "#B53389" },
    { name: "Fandango pink", code: "#DE5285" },
    { name: "Fashion fuchsia", code: "#F400A1" },
    { name: "Fawn", code: "#E5AA70" },
    { name: "Feldgrau", code: "#4D5D53" },
    { name: "Fern green", code: "#4F7942" },
    { name: "Field drab", code: "#6C541E" },
    { name: "Fiery rose", code: "#FF5470" },
    { name: "Firebrick", code: "#B22222" },
    { name: "Fire engine red", code: "#CE2029" },
    { name: "Fire opal", code: "#E95C4B" },
    { name: "Flame", code: "#E25822" },
    { name: "Flax", code: "#EEDC82" },
    { name: "Flirt", code: "#A2006D" },
    { name: "Floral white", code: "#FFFAF0" },
    { name: "Fluorescent blue", code: "#15F4EE" },
    { name: "Forest green(Crayola)", code: "#5FA777" },
    { name: "Forest green(traditional)", code: "#014421" },
    { name: "Forest green(web)", code: "#228B22" },
    { name: "French beige", code: "#A67B5B" },
    { name: "French bistre", code: "#856D4D" },
    { name: "French blue", code: "#0072BB" },
    { name: "French fuchsia", code: "#FD3F92" },
    { name: "French lilac", code: "#86608E" },
    { name: "French lime", code: "#9EFD38" },
    { name: "French mauve", code: "#D473D4" },
    { name: "French pink", code: "#FD6C9E" },
    { name: "French raspberry", code: "#C72C48" },
    { name: "French rose", code: "#F64A8A" },
    { name: "French sky blue", code: "#77B5FE" },
    { name: "French violet", code: "#8806CE" },
    { name: "Frostbite", code: "#E936A7" },
    { name: "Fuchsia", code: "#FF00FF" },
    { name: "Fuchsia(Crayola)", code: "#C154C1" },
    { name: "Fuchsia purple", code: "#CC397B" },
    { name: "Fuchsia rose", code: "#C74375" },
    { name: "Fulvous", code: "#E48400" },
    { name: "Fuzzy Wuzzy", code: "#87421F" }
]